### PR TITLE
Renewed Pull Request

### PR DESCRIPTION
**Pull request by apmuthu**
OPEN_PORT to be added

### CODE REVIEW

**Comment by jact** [comment]
All-in-one SQL file is not necessary (also, the path is incorrect, because exists a folder named 'sql' inside install).

**Comment by apmuthu** [comment]
It is being kept outside the `sql` folder to avoid having it executed along with the others in it. See if you want it to replace all the others there and then move it into the `sql` folder.

**Comment by jact** [comment]
It is not a good idea to replace the other .sql files, so the all-in-one file is not necessary. The installation system is well thought out as it is.

**Comment by apmuthu** [comment]
Most applications have a single sql file to get the job done. Attempting to create individual tables using separate sql files makes it cumbersome. To make it easier, there can be a single sql script file that "includes" / "executes" these individual sql files if the single opened out sql file I provided does not suit the project.

The missing db OPEN_PORT constant can be defined too.

**Pull request closed without merging**
